### PR TITLE
Fixes issue #2 by handling certain message types with custom response parsers

### PR DESCRIPTION
**Pull request by markwoodhall**

### CODE REVIEW

**Comment by Gavlooth** [comment]
No the  sayid buffer returns completely empty.

**Comment by markwoodhall** [comment]
When does that happen?

**Comment by gavlooth** [comment]
Sorry it was My mistake. I run neovim from wsl and the  repl from windows. This causes gst to evaluate /mnt/c/path/to/file instead a c:\path\to\file . I haven't tried yet to evaluate from a windows neovim or from a complete linux distro repl, i will try the first later and the second on monday.
 By the way the evaluation thing is a problem of the vim plugin or of sayid itself ?

**Comment by markwoodhall** [comment]
I'm not entirely sure, it could be that it is the vim-fireplace plugin that
doesn't like neovim running in WSL and the repl running in windows. Can you
eval Clojure code like that?

**Comment by gavlooth** [comment]
Yes clojure code evals as normal, docstring are displayed from vim-fireplace e.t.c. e.t.c. 
 Maybe vim-sayid or sayid itself doesnt eval from the classpath and expands from the root path ?

**Comment by gavlooth** [comment]
I tried it in the work it doesnt seem to fix the issue aside from the initial buffer poping with gsw. I attached some screenshots in the issue comments

**Comment by gavlooth** [comment]
Ok Cloning from your repository works except gsq, tracing functions
Thank you very much :)

**Comment by markwoodhall** [comment]
@Gavlooth perfect, if you try the latest version then `gsq` should work as well.

**Comment by markwoodhall** [comment]
Is there any chance to get this merged?

**Pull request closed without merging**
